
CREATE TABLE INVPAY.DICT_PROG (
  CODE_PROG       NUMBER,
  NAME_PROG_FULL  NVARCHAR2(100),
  NAME_PROG_SHORT NVARCHAR2(50),
  CONSTRAINT PK_DICT_PROG_ID_PROG PRIMARY KEY (CODE_PROG) USING INDEX TABLESPACE USERS STORAGE (INITIAL 64 K
                                                                                                MAXEXTENTS UNLIMITED)
)
TABLESPACE USERS
STORAGE (INITIAL 64 K
         MAXEXTENTS UNLIMITED)
LOGGING;

COMMENT ON TABLE INVPAY.DICT_PROG IS 'Список программ для выставления счетов';
COMMENT ON COLUMN INVPAY.DICT_PROG.CODE_PROG IS 'Идентификатор ПО';
COMMENT ON COLUMN INVPAY.DICT_PROG.NAME_PROG_FULL IS 'Полное наименование ПО';
COMMENT ON COLUMN INVPAY.DICT_PROG.NAME_PROG_SHORT IS 'Краткое наименование ПО';

COMMIT;