--
CREATE TABLE INVPAY.DICT_MONTH (
  CODE_MONTH NUMBER(2, 0),
  NAME_MONTH NVARCHAR2(50) NOT NULL,
  CONSTRAINT PK_DICT_MONTH_CODE_MONTH PRIMARY KEY (CODE_MONTH) USING INDEX TABLESPACE USERS STORAGE (INITIAL 64 K
                                                                                                     MAXEXTENTS UNLIMITED)
)
TABLESPACE USERS
STORAGE (INITIAL 64 K
         MAXEXTENTS UNLIMITED)
LOGGING;

COMMENT ON TABLE INVPAY.DICT_MONTH IS 'Справочник названий месяцев';
COMMENT ON COLUMN INVPAY.DICT_MONTH.CODE_MONTH IS 'Номер месяца';
COMMENT ON COLUMN INVPAY.DICT_MONTH.NAME_MONTH IS 'Название';

COMMIT;