CREATE TABLE INVPAY.DICT_PROG_POINT (
  CODE_PROG_POINT NUMBER         NOT NULL,
  NAME_PROG_POINT NVARCHAR2(200) NOT NULL,
  NAME_UNIT       NVARCHAR2(50),
  COST_ONE        NUMBER(7, 2),
  CODE_PROG       NUMBER         NOT NULL,
  DATE_START      NVARCHAR2(50),
  CONSTRAINT PK_DICT_PROG_POINT_CODE_PROG_P PRIMARY KEY (CODE_PROG_POINT) USING INDEX TABLESPACE USERS STORAGE (INITIAL 64 K
                                                                                                                MAXEXTENTS UNLIMITED),
  CONSTRAINT FK_DICT_PROG_POINT_CODE_PROG FOREIGN KEY (CODE_PROG)
  REFERENCES INVPAY.DICT_PROG (CODE_PROG) ON DELETE CASCADE
)
TABLESPACE USERS
STORAGE (INITIAL 64 K
         MAXEXTENTS UNLIMITED)
LOGGING;

COMMENT ON TABLE INVPAY.DICT_PROG_POINT IS 'Связь ПО с услуугами (для заполнения таблицы счета)';
COMMENT ON COLUMN INVPAY.DICT_PROG_POINT.CODE_PROG IS 'Идентификатор привязанной программы';
COMMENT ON COLUMN INVPAY.DICT_PROG_POINT.CODE_PROG_POINT IS 'Идентификатор услуги';
COMMENT ON COLUMN INVPAY.DICT_PROG_POINT.COST_ONE IS 'Стоимость еденицы, без НДС';
COMMENT ON COLUMN INVPAY.DICT_PROG_POINT.DATE_START IS 'Дата начала действия';
COMMENT ON COLUMN INVPAY.DICT_PROG_POINT.NAME_PROG_POINT IS 'Наименование услуги';
COMMENT ON COLUMN INVPAY.DICT_PROG_POINT.NAME_UNIT IS 'Еденица измерения';

--
-- Создать внешний ключ "FK_DICT_PROG_POINT_CODE_PROG" для объекта типа таблица "INVPAY"."DICT_PROG_POINT"
--
ALTER TABLE INVPAY.DICT_PROG_POINT
ADD CONSTRAINT FK_DICT_PROG_POINT_CODE_PROG FOREIGN KEY (CODE_PROG)
REFERENCES INVPAY.DICT_PROG (CODE_PROG) ON DELETE CASCADE;

COMMIT;