CREATE TABLE INVPAY.DICT_ROLE (
  CODE_ROLE NUMBER,
  NAME_ROLE NVARCHAR2(50),
  CONSTRAINT KEY_DICT_ROLE_CODE_ROLE UNIQUE (CODE_ROLE) USING INDEX TABLESPACE USERS STORAGE (INITIAL 64 K
                                                                                              MAXEXTENTS UNLIMITED)
)
TABLESPACE USERS
STORAGE (INITIAL 64 K
         MAXEXTENTS UNLIMITED)
LOGGING;

COMMENT ON TABLE INVPAY.DICT_ROLE IS 'Справочник ролей пользователей';