CREATE TABLE INVPAY.DICT_BANK_INFO (
  CODE_ORG        NUMBER,
  NAME_ORG        VARCHAR2(1024 BYTE),
  UNP             NUMBER,
  ADDRESS_INFO    NVARCHAR2(500),
  PAYMENT_ACCOUNT NVARCHAR2(50),
  BANK            NVARCHAR2(500),
  IS_NEW_ORG      NUMBER(1, 0),
  CONSTRAINT PK_DICT_BANK_INFO_CODE_ORG PRIMARY KEY (CODE_ORG) USING INDEX TABLESPACE USERS STORAGE (INITIAL 64 K
                                                                                                     MAXEXTENTS UNLIMITED)
)
TABLESPACE USERS
STORAGE (INITIAL 64 K
         MAXEXTENTS UNLIMITED)
LOGGING;

COMMENT ON TABLE INVPAY.DICT_BANK_INFO IS 'Информация о банковских реквизитах организаций';
COMMENT ON COLUMN INVPAY.DICT_BANK_INFO.ADDRESS_INFO IS 'Адрес организации';
COMMENT ON COLUMN INVPAY.DICT_BANK_INFO.BANK IS 'Адрес банка';
COMMENT ON COLUMN INVPAY.DICT_BANK_INFO.CODE_ORG IS 'Идентификатор организации';
COMMENT ON COLUMN INVPAY.DICT_BANK_INFO.IS_NEW_ORG IS 'Признак добавления организацци вручную';
COMMENT ON COLUMN INVPAY.DICT_BANK_INFO.NAME_ORG IS 'Наименование организации (для ИП)';
COMMENT ON COLUMN INVPAY.DICT_BANK_INFO.PAYMENT_ACCOUNT IS 'Расчетный счет';
COMMENT ON COLUMN INVPAY.DICT_BANK_INFO.UNP IS 'УНП';