
INSERT INTO INVPAY.DICT_MONTH(CODE_MONTH, NAME_MONTH) VALUES
(1, N'январь');
INSERT INTO INVPAY.DICT_MONTH(CODE_MONTH, NAME_MONTH) VALUES
(2, N'февраль');
INSERT INTO INVPAY.DICT_MONTH(CODE_MONTH, NAME_MONTH) VALUES
(3, N'март');
INSERT INTO INVPAY.DICT_MONTH(CODE_MONTH, NAME_MONTH) VALUES
(4, N'апрель');
INSERT INTO INVPAY.DICT_MONTH(CODE_MONTH, NAME_MONTH) VALUES
(5, N'май');
INSERT INTO INVPAY.DICT_MONTH(CODE_MONTH, NAME_MONTH) VALUES
(6, N'июнь');
INSERT INTO INVPAY.DICT_MONTH(CODE_MONTH, NAME_MONTH) VALUES
(7, N'июль');
INSERT INTO INVPAY.DICT_MONTH(CODE_MONTH, NAME_MONTH) VALUES
(8, N'август');
INSERT INTO INVPAY.DICT_MONTH(CODE_MONTH, NAME_MONTH) VALUES
(9, N'сентябрь');
INSERT INTO INVPAY.DICT_MONTH(CODE_MONTH, NAME_MONTH) VALUES
(10, N'октябрь');
INSERT INTO INVPAY.DICT_MONTH(CODE_MONTH, NAME_MONTH) VALUES
(11, N'ноябрь');
INSERT INTO INVPAY.DICT_MONTH(CODE_MONTH, NAME_MONTH) VALUES
(12, N'декабрь');

INSERT INTO INVPAY.DICT_PROG(CODE_PROG, NAME_PROG_FULL, NAME_PROG_SHORT) VALUES
(1, N'АРМ "Лесопользование-3"', N'АРМ ЛП');
INSERT INTO INVPAY.DICT_PROG(CODE_PROG, NAME_PROG_FULL, NAME_PROG_SHORT) VALUES
(2, N'ГисЛес', N'ГИС');

INSERT INTO INVPAY.DICT_PROG_POINT(CODE_PROG_POINT, NAME_PROG_POINT, NAME_UNIT, COST_ONE, CODE_PROG, DATE_START) VALUES
(1, N'Обслуживание программного продукта АРМ "Лесопользование-3"', N'МЕС.', 55.42, 1, N'22.03.2019');
INSERT INTO INVPAY.DICT_PROG_POINT(CODE_PROG_POINT, NAME_PROG_POINT, NAME_UNIT, COST_ONE, CODE_PROG, DATE_START) VALUES
(2, N'Загрузка в Мобильную ГисЛес', N'КАРТА', 21.65, 2, N'18.10.2019');
INSERT INTO INVPAY.DICT_PROG_POINT(CODE_PROG_POINT, NAME_PROG_POINT, NAME_UNIT, COST_ONE, CODE_PROG, DATE_START) VALUES
(3, N'Формирование электронного ключа', N'КЛЮЧ', 1.01, 2, N'18.10.2019');

COMMIT;
