INSERT INTO INVPAY.DICT_ROLE VALUES (1, 'Администратор');
INSERT INTO INVPAY.DICT_ROLE VALUES (2, 'ФЭО');
INSERT INTO INVPAY.DICT_ROLE VALUES (3, 'Бухгалтерия');
INSERT INTO INVPAY.DICT_ROLE VALUES (4, 'Гл.бухгалтер');
INSERT INTO INVPAY.DICT_ROLE VALUES (5, 'Оператор программы');
COMMIT;

INSERT INTO INVPAY.USERS VALUES ('admin', NULL, 1, 'Администратор', 0, NULL);
COMMIT;