
CREATE TABLE INVPAY.INVOICE (
  ID_INVOICE     NUMBER,
  NUM_INVOICE    NUMBER,
  DATE_INVOICE   NVARCHAR2(50),
  CODE_ORG       NUMBER,
  CODE_PROG      NUMBER,
  DATE_PAID      NVARCHAR2(50),
  DATE_START_EXT NVARCHAR2(50),
  DATE_END_EXT   NVARCHAR2(50),
  SUM_PAID       NUMBER(7, 2),
  NOTE           NVARCHAR2(200),
  CONSTRAINT PK_INVOICE_ID_INVOICE PRIMARY KEY (ID_INVOICE) USING INDEX TABLESPACE USERS STORAGE (INITIAL 64 K
                                                                                                  MAXEXTENTS UNLIMITED)
)
TABLESPACE USERS
STORAGE (INITIAL 64 K
         MAXEXTENTS UNLIMITED)
LOGGING;

COMMENT ON TABLE INVPAY.INVOICE IS 'Таблица счетов';
COMMENT ON COLUMN INVPAY.INVOICE.CODE_ORG IS 'Идентификатор организации';
COMMENT ON COLUMN INVPAY.INVOICE.CODE_PROG IS 'Идентификатор ПО';
COMMENT ON COLUMN INVPAY.INVOICE.DATE_END_EXT IS 'Срок окончания действия ключа';
COMMENT ON COLUMN INVPAY.INVOICE.DATE_INVOICE IS 'Дата выставления';
COMMENT ON COLUMN INVPAY.INVOICE.DATE_PAID IS 'Дата оплаты';
COMMENT ON COLUMN INVPAY.INVOICE.DATE_START_EXT IS 'Срок начала действия ключа';
COMMENT ON COLUMN INVPAY.INVOICE.ID_INVOICE IS 'Идентификатор записи';
COMMENT ON COLUMN INVPAY.INVOICE.NOTE IS 'Замечания';
COMMENT ON COLUMN INVPAY.INVOICE.NUM_INVOICE IS 'Номер счета';
COMMENT ON COLUMN INVPAY.INVOICE.SUM_PAID IS 'Сумма оплаты';

--
-- Создать внешний ключ "FK_INVOICE_CODE_PROG" для объекта типа таблица "INVPAY"."INVOICE"
--
ALTER TABLE INVPAY.INVOICE
ADD CONSTRAINT FK_INVOICE_CODE_PROG FOREIGN KEY (CODE_PROG)
REFERENCES INVPAY.DICT_PROG (CODE_PROG) ON DELETE CASCADE;

COMMIT;