CREATE TABLE INVPAY.USERS (
  LOGGIN     NVARCHAR2(50),
  PASSWORD   NVARCHAR2(50),
  ROLE       NUMBER(2, 0),
  FIO        NVARCHAR2(100),
  CODE_PROG  NUMBER(2, 0),
  IS_BLOCKED NUMBER(1, 0),
  CONSTRAINT FK_USERS_ROLE FOREIGN KEY (ROLE)
  REFERENCES INVPAY.DICT_ROLE (CODE_ROLE) ON DELETE SET NULL
)
TABLESPACE USERS
STORAGE (INITIAL 64 K
         MAXEXTENTS UNLIMITED)
LOGGING;

COMMENT ON TABLE INVPAY.USERS IS 'Пользователи системы';
COMMENT ON COLUMN INVPAY.USERS.CODE_PROG IS '0-все программы, иначе конкретная программа';